#!/usr/bin/env python3
"""Embed web/data/*.json files into a single JS file for standalone browser use.

Usage:
    python scripts/embed_hsap_data.py

Output:
    web/js/hsap_data.js
"""

import json
from pathlib import Path

WEB_DATA_DIR = Path(__file__).resolve().parent.parent / "web" / "data"
OUT_PATH = Path(__file__).resolve().parent.parent / "web" / "js" / "hsap_data.js"

SCENARIOS = [
    "A_normal_baseline",
    "B_hsap_abundance",
    "C_crowded_abundance",
    "D_high_predation_survival",
    "E_behavioral_sink_recovery",
    "F_behavioral_sink_extinction",
]


def main():
    data = {}
    for name in SCENARIOS:
        json_path = WEB_DATA_DIR / f"{name}.json"
        if not json_path.exists():
            print(f"  SKIP {name}: {json_path} not found")
            continue
        with open(json_path, "r") as f:
            data[name] = json.load(f)
        n_frames = len(data[name].get("frames", []))
        print(f"  Loaded {name}: {n_frames} frames")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_PATH, "w") as f:
        f.write("/* Auto-generated by scripts/embed_hsap_data.py — do not edit manually */\n")
        f.write("const HSAP_DATA = ")
        json.dump(data, f, separators=(",", ":"))
        f.write(";\n")

    size_mb = OUT_PATH.stat().st_size / (1024 * 1024)
    print(f"\nWrote {OUT_PATH} ({size_mb:.1f} MB)")
    print(f"Scenarios embedded: {len(data)}")


if __name__ == "__main__":
    main()
